### PR TITLE
Make prevCapture persist into nested parses

### PR DESCRIPTION
**Pull request by FuegoFro**
This pulls the `prevCapture` out to be "global" state for the parses and persist into nested invocations of `nestedParse`. This allows rules to determine if they are truly at the beginning of a line (by seeing if `prevCapture` is either empty or ends with a newline). Before, the `prevCapture` would reset at each nesting, so it would only allow you to determine if you were at the beginning of the nested parse, but not necessarily the line.

There are other approaches to preserving this data (such as passing `prevCapture` into the recursive `nestedParse` call) but these all either created more functions at runtime or broke the API, requiring clients to change their method signatures.

### CODE REVIEW

**Comment by paulshen** [comment]
Would it be safer to add a new arg to `match(source, state, prevCapture, discordGlobalPrevCapture)`? as a new engineer unfamiliar with the fork, i'd expect it work as open source and i can see the differing behavior to be a source of bamboozle.

**Comment by FuegoFro** [comment]
I'm... also unfamiliar with the fork. We currently actually use https://github.com/mgreer/simple-markdown in production haha (I just pushed the branch we use from the fork to this one and based this PR off of it).

But in any case, that's a good idea given JS's argument-dropping behavior and I agree it makes things less surprising 🙂 I'll make that change

**Comment by paulshen** [comment]
While we're here, can we update our `simple-markdown`? @night says there are a number of updates, including xss fixes.

Looks like the API has been renamed to [`lookbehind`](https://github.com/Khan/simple-markdown#matchsource-state-lookbehind). Plus points if we can get this back into master

**Comment by FuegoFro** [comment]
Heh, we certainly could try. That seemed like a bigger/scarier change, but I'm happy to try it 🙂

**Comment by night** [comment]
we really shouldn't have a reason to have a fork. stan's change + greer's react change were upstream fixed a while ago. if the latest master on simple-markdown doesn't fix what you're trying to do, would totally recommend opening a PR/issue on the upstream repo and mentioning ariabuckles (she's been super helpful in the past)

**Comment by FuegoFro** [comment]
I'm going to close this and open a PR against upstream instead 🙂

**Pull request closed without merging**
